# Generated by Django 4.0.4 on 2022-08-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=50)),
            ],
        ),
    ]
