# Generated by Django 4.1 on 2022-09-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('rating', models.FloatField()),
                ('recomendado', models.BooleanField(default=True)),
                ('categoria', models.CharField(default='N/A', max_length=50)),
                ('url', models.CharField(default='N/A', max_length=200)),
                ('imagen', models.CharField(default='N/A', max_length=200)),
            ],
        ),
    ]
