# Generated by Django 4.1 on 2022-09-30 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='price',
            new_name='precio',
        ),
    ]
