# Generated by Django 4.1 on 2022-10-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_producto_primer_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='rating_modelo',
            field=models.FloatField(default=0.0),
        ),
    ]
